trigger:
- none

pool:
  vmImage: 'ubuntu-latest'  # Define the VM image to use

variables:
- group: my-variable-group
- name: my-passed-variable
  value: $[variables.myhello]
- script: echo $(my-passed-variable)
