trigger:
- none  # No automatic trigger; pipeline must be manually triggered

pool:
  vmImage: 'ubuntu-latest'  # Define the VM image to use

variables:
- group: Contoso Variable Group  # Reference the variable group
  
jobs:
- job: mypassedvariable
  steps:
  - script: echo 'va $(va)'
    displayName: 'define variable groups'
