trigger:
- none

pool:
  vmImage: 'ubuntu-latest'  # Define the VM image to use

variables:
- group: my-variable-group
- name: my-passed-variable
  value: $[variables.myhello]
  
jobs:
- job: mypassedvariable
  steps:
  - script: echo $(my-passed-variable)
    displayName: 'define variable groups'
