yaml
Copy code
trigger:
- none  # No automatic trigger; pipeline must be manually triggered

pool:
  vmImage: 'ubuntu-latest'  # Define the VM image to use

variables:
- group: my-variable-group  # Reference the variable group
- name: my-passed-variable
  value: $(myhello)  # Correct syntax to reference another variable
  
jobs:
- job: mypassedvariable
  steps:
  - script: echo 'passedvariable: $(my-passed-variable)'
    displayName: 'define variable groups'
